- name: Auto connect collector
  hosts: gns3
  gather_facts: no
  become: true
  vars:
    ansible_user: "{{ linux_user }}"
    ansible_password: "{{ linux_user_password }}"
    ansible_become_password: "{{ linux_user_password }}"
    ansible_connection: ssh
    reconnection_retries: 10
    timeout: 60
    gns3_server: "http://10.255.255.100"
    gns3_project: "COBRA DEN"
    node_links:
      - ["collector", "Ethernet1", "External", "eth7"]
      - ["collector", "Ethernet2", "DMZ", "eth7"]
      - ["collector", "Ethernet3", "Internal", "eth7"]
      - ["collector", "Ethernet4", "CN-RTR-1", "eth7"]
      - ["collector", "Ethernet5", "CN-RTR-2", "eth7"]
      - ["collector", "Ethernet6", "CN-RTR-3", "eth7"]
      - ["collector", "Ethernet7", "CN-RTR-4", "eth7"]
  collections:
    - davidban77.gns3
  tasks:
    - name: Auto-tap routers
      gns3_project:
        url: "{{ gns3_server }}"
        project_name: "{{ gns3_project }}"
        links_spec: "{{ node_links }}"
        state: absent